CREATE TABLE IF NOT EXISTS resources (
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    resource varchar(100) NOT NULL DEFAULT ''
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;